// <auto-generated />
using System;
using System.Text.Json;
using AuditLogService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditLogService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditLogDbContext))]
    [Migration("20261003055427_AddAuditEventArchives")]
    partial class AddAuditEventArchives
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditLogService.Infrastructure.Persistence.AuditEventArchive", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.HasKey("EventId")
                        .HasName("pk_audit_event_archives");

                    b.ToTable("audit_event_archives", (string)null);
                });

            modelBuilder.Entity("AuditLogService.Infrastructure.Persistence.AuditEventRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("previous_hash");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resource_type");

                    b.Property<long>("SequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("EventId")
                        .HasName("pk_audit_events");

                    b.HasIndex("ActorId")
                        .HasDatabaseName("ix_audit_events_actor_id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("ix_audit_events_event_type");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_events_sequence_number");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_events_timestamp");

                    b.HasIndex("ResourceType", "ResourceId")
                        .HasDatabaseName("ix_audit_events_resource_type_resource_id");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_events_actor_id_not_empty", "length(btrim(actor_id)) > 0");

                            t.HasCheckConstraint("ck_audit_events_content_hash_format", "content_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_audit_events_event_type_not_empty", "length(btrim(event_type)) > 0");

                            t.HasCheckConstraint("ck_audit_events_payload_object", "jsonb_typeof(payload) = 'object'");

                            t.HasCheckConstraint("ck_audit_events_previous_hash_format", "previous_hash = 'GENESIS' OR previous_hash ~ '^[0-9a-f]{64}$'");

                            t.HasCheckConstraint("ck_audit_events_resource_id_not_empty", "length(btrim(resource_id)) > 0");

                            t.HasCheckConstraint("ck_audit_events_resource_type_not_empty", "length(btrim(resource_type)) > 0");

                            t.HasCheckConstraint("ck_audit_events_sequence_positive", "sequence_number > 0");
                        });
                });

            modelBuilder.Entity("AuditLogService.Infrastructure.Persistence.ChainMetadata", b =>
                {
                    b.Property<int>("ChainId")
                        .HasColumnType("integer")
                        .HasColumnName("chain_id");

                    b.Property<string>("HeadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("head_hash");

                    b.Property<long>("HeadSequenceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("head_sequence_number");

                    b.HasKey("ChainId")
                        .HasName("pk_chain_metadata");

                    b.ToTable("chain_metadata", null, t =>
                        {
                            t.HasCheckConstraint("ck_chain_metadata_head_hash_format", "(head_sequence_number = 0 AND head_hash = 'GENESIS') OR (head_sequence_number > 0 AND head_hash ~ '^[0-9a-f]{64}$')");

                            t.HasCheckConstraint("ck_chain_metadata_head_sequence_nonnegative", "head_sequence_number >= 0");

                            t.HasCheckConstraint("ck_chain_metadata_single_global_chain", "chain_id = 1");
                        });

                    b.HasData(
                        new
                        {
                            ChainId = 1,
                            HeadHash = "GENESIS",
                            HeadSequenceNumber = 0L
                        });
                });

            modelBuilder.Entity("AuditLogService.Infrastructure.Persistence.AuditEventArchive", b =>
                {
                    b.HasOne("AuditLogService.Infrastructure.Persistence.AuditEventRecord", null)
                        .WithOne()
                        .HasForeignKey("AuditLogService.Infrastructure.Persistence.AuditEventArchive", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
